//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsShoppingCart.TransactionWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.mcda5510.dpenny.com", ConfigurationName="TransactionWebService.TrxnWebService")]
    public interface TrxnWebService {
        
        // CODEGEN: Generating message contract since element name getTransactionReturn from namespace http://service.mcda5510.dpenny.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CmsShoppingCart.TransactionWebService.getTransactionResponse getTransaction(CmsShoppingCart.TransactionWebService.getTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CmsShoppingCart.TransactionWebService.getTransactionResponse> getTransactionAsync(CmsShoppingCart.TransactionWebService.getTransactionRequest request);
        
        // CODEGEN: Generating message contract since element name nameOnCard from namespace http://service.mcda5510.dpenny.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CmsShoppingCart.TransactionWebService.insertRecordsResponse insertRecords(CmsShoppingCart.TransactionWebService.insertRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CmsShoppingCart.TransactionWebService.insertRecordsResponse> insertRecordsAsync(CmsShoppingCart.TransactionWebService.insertRecordsRequest request);
        
        // CODEGEN: Generating message contract since element name deleteResultsReturn from namespace http://service.mcda5510.dpenny.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CmsShoppingCart.TransactionWebService.deleteResultsResponse deleteResults(CmsShoppingCart.TransactionWebService.deleteResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CmsShoppingCart.TransactionWebService.deleteResultsResponse> deleteResultsAsync(CmsShoppingCart.TransactionWebService.deleteResultsRequest request);
        
        // CODEGEN: Generating message contract since element name nameOnCard from namespace http://service.mcda5510.dpenny.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CmsShoppingCart.TransactionWebService.updateTransactionResponse updateTransaction(CmsShoppingCart.TransactionWebService.updateTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CmsShoppingCart.TransactionWebService.updateTransactionResponse> updateTransactionAsync(CmsShoppingCart.TransactionWebService.updateTransactionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTransaction", Namespace="http://service.mcda5510.dpenny.com", Order=0)]
        public CmsShoppingCart.TransactionWebService.getTransactionRequestBody Body;
        
        public getTransactionRequest() {
        }
        
        public getTransactionRequest(CmsShoppingCart.TransactionWebService.getTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mcda5510.dpenny.com")]
    public partial class getTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int trxnID;
        
        public getTransactionRequestBody() {
        }
        
        public getTransactionRequestBody(int trxnID) {
            this.trxnID = trxnID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTransactionResponse", Namespace="http://service.mcda5510.dpenny.com", Order=0)]
        public CmsShoppingCart.TransactionWebService.getTransactionResponseBody Body;
        
        public getTransactionResponse() {
        }
        
        public getTransactionResponse(CmsShoppingCart.TransactionWebService.getTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mcda5510.dpenny.com")]
    public partial class getTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTransactionReturn;
        
        public getTransactionResponseBody() {
        }
        
        public getTransactionResponseBody(string getTransactionReturn) {
            this.getTransactionReturn = getTransactionReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertRecordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertRecords", Namespace="http://service.mcda5510.dpenny.com", Order=0)]
        public CmsShoppingCart.TransactionWebService.insertRecordsRequestBody Body;
        
        public insertRecordsRequest() {
        }
        
        public insertRecordsRequest(CmsShoppingCart.TransactionWebService.insertRecordsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mcda5510.dpenny.com")]
    public partial class insertRecordsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int trxnID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nameOnCard;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double unitPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int qty;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double totalPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string expDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string creditCardType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public long cardNum;
        
        public insertRecordsRequestBody() {
        }
        
        public insertRecordsRequestBody(int trxnID, string nameOnCard, string CardNumber, double unitPrice, int qty, double totalPrice, string expDate, string creditCardType, long cardNum) {
            this.trxnID = trxnID;
            this.nameOnCard = nameOnCard;
            this.CardNumber = CardNumber;
            this.unitPrice = unitPrice;
            this.qty = qty;
            this.totalPrice = totalPrice;
            this.expDate = expDate;
            this.creditCardType = creditCardType;
            this.cardNum = cardNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertRecordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertRecordsResponse", Namespace="http://service.mcda5510.dpenny.com", Order=0)]
        public CmsShoppingCart.TransactionWebService.insertRecordsResponseBody Body;
        
        public insertRecordsResponse() {
        }
        
        public insertRecordsResponse(CmsShoppingCart.TransactionWebService.insertRecordsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mcda5510.dpenny.com")]
    public partial class insertRecordsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertRecordsReturn;
        
        public insertRecordsResponseBody() {
        }
        
        public insertRecordsResponseBody(string insertRecordsReturn) {
            this.insertRecordsReturn = insertRecordsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteResults", Namespace="http://service.mcda5510.dpenny.com", Order=0)]
        public CmsShoppingCart.TransactionWebService.deleteResultsRequestBody Body;
        
        public deleteResultsRequest() {
        }
        
        public deleteResultsRequest(CmsShoppingCart.TransactionWebService.deleteResultsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mcda5510.dpenny.com")]
    public partial class deleteResultsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int trxId;
        
        public deleteResultsRequestBody() {
        }
        
        public deleteResultsRequestBody(int trxId) {
            this.trxId = trxId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteResultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteResultsResponse", Namespace="http://service.mcda5510.dpenny.com", Order=0)]
        public CmsShoppingCart.TransactionWebService.deleteResultsResponseBody Body;
        
        public deleteResultsResponse() {
        }
        
        public deleteResultsResponse(CmsShoppingCart.TransactionWebService.deleteResultsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mcda5510.dpenny.com")]
    public partial class deleteResultsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteResultsReturn;
        
        public deleteResultsResponseBody() {
        }
        
        public deleteResultsResponseBody(string deleteResultsReturn) {
            this.deleteResultsReturn = deleteResultsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateTransaction", Namespace="http://service.mcda5510.dpenny.com", Order=0)]
        public CmsShoppingCart.TransactionWebService.updateTransactionRequestBody Body;
        
        public updateTransactionRequest() {
        }
        
        public updateTransactionRequest(CmsShoppingCart.TransactionWebService.updateTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mcda5510.dpenny.com")]
    public partial class updateTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int trxnID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nameOnCard;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CardNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double unitPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int qty;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double totalPrice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string expDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string creditCardType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public long cardNum;
        
        public updateTransactionRequestBody() {
        }
        
        public updateTransactionRequestBody(int trxnID, string nameOnCard, string CardNumber, double unitPrice, int qty, double totalPrice, string expDate, string creditCardType, long cardNum) {
            this.trxnID = trxnID;
            this.nameOnCard = nameOnCard;
            this.CardNumber = CardNumber;
            this.unitPrice = unitPrice;
            this.qty = qty;
            this.totalPrice = totalPrice;
            this.expDate = expDate;
            this.creditCardType = creditCardType;
            this.cardNum = cardNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateTransactionResponse", Namespace="http://service.mcda5510.dpenny.com", Order=0)]
        public CmsShoppingCart.TransactionWebService.updateTransactionResponseBody Body;
        
        public updateTransactionResponse() {
        }
        
        public updateTransactionResponse(CmsShoppingCart.TransactionWebService.updateTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.mcda5510.dpenny.com")]
    public partial class updateTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateTransactionReturn;
        
        public updateTransactionResponseBody() {
        }
        
        public updateTransactionResponseBody(string updateTransactionReturn) {
            this.updateTransactionReturn = updateTransactionReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TrxnWebServiceChannel : CmsShoppingCart.TransactionWebService.TrxnWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrxnWebServiceClient : System.ServiceModel.ClientBase<CmsShoppingCart.TransactionWebService.TrxnWebService>, CmsShoppingCart.TransactionWebService.TrxnWebService {
        
        public TrxnWebServiceClient() {
        }
        
        public TrxnWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrxnWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrxnWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrxnWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CmsShoppingCart.TransactionWebService.getTransactionResponse CmsShoppingCart.TransactionWebService.TrxnWebService.getTransaction(CmsShoppingCart.TransactionWebService.getTransactionRequest request) {
            return base.Channel.getTransaction(request);
        }
        
        public string getTransaction(int trxnID) {
            CmsShoppingCart.TransactionWebService.getTransactionRequest inValue = new CmsShoppingCart.TransactionWebService.getTransactionRequest();
            inValue.Body = new CmsShoppingCart.TransactionWebService.getTransactionRequestBody();
            inValue.Body.trxnID = trxnID;
            CmsShoppingCart.TransactionWebService.getTransactionResponse retVal = ((CmsShoppingCart.TransactionWebService.TrxnWebService)(this)).getTransaction(inValue);
            return retVal.Body.getTransactionReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CmsShoppingCart.TransactionWebService.getTransactionResponse> CmsShoppingCart.TransactionWebService.TrxnWebService.getTransactionAsync(CmsShoppingCart.TransactionWebService.getTransactionRequest request) {
            return base.Channel.getTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CmsShoppingCart.TransactionWebService.getTransactionResponse> getTransactionAsync(int trxnID) {
            CmsShoppingCart.TransactionWebService.getTransactionRequest inValue = new CmsShoppingCart.TransactionWebService.getTransactionRequest();
            inValue.Body = new CmsShoppingCart.TransactionWebService.getTransactionRequestBody();
            inValue.Body.trxnID = trxnID;
            return ((CmsShoppingCart.TransactionWebService.TrxnWebService)(this)).getTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CmsShoppingCart.TransactionWebService.insertRecordsResponse CmsShoppingCart.TransactionWebService.TrxnWebService.insertRecords(CmsShoppingCart.TransactionWebService.insertRecordsRequest request) {
            return base.Channel.insertRecords(request);
        }
        
        public string insertRecords(int trxnID, string nameOnCard, string CardNumber, double unitPrice, int qty, double totalPrice, string expDate, string creditCardType, long cardNum) {
            CmsShoppingCart.TransactionWebService.insertRecordsRequest inValue = new CmsShoppingCart.TransactionWebService.insertRecordsRequest();
            inValue.Body = new CmsShoppingCart.TransactionWebService.insertRecordsRequestBody();
            inValue.Body.trxnID = trxnID;
            inValue.Body.nameOnCard = nameOnCard;
            inValue.Body.CardNumber = CardNumber;
            inValue.Body.unitPrice = unitPrice;
            inValue.Body.qty = qty;
            inValue.Body.totalPrice = totalPrice;
            inValue.Body.expDate = expDate;
            inValue.Body.creditCardType = creditCardType;
            inValue.Body.cardNum = cardNum;
            CmsShoppingCart.TransactionWebService.insertRecordsResponse retVal = ((CmsShoppingCart.TransactionWebService.TrxnWebService)(this)).insertRecords(inValue);
            return retVal.Body.insertRecordsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CmsShoppingCart.TransactionWebService.insertRecordsResponse> CmsShoppingCart.TransactionWebService.TrxnWebService.insertRecordsAsync(CmsShoppingCart.TransactionWebService.insertRecordsRequest request) {
            return base.Channel.insertRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CmsShoppingCart.TransactionWebService.insertRecordsResponse> insertRecordsAsync(int trxnID, string nameOnCard, string CardNumber, double unitPrice, int qty, double totalPrice, string expDate, string creditCardType, long cardNum) {
            CmsShoppingCart.TransactionWebService.insertRecordsRequest inValue = new CmsShoppingCart.TransactionWebService.insertRecordsRequest();
            inValue.Body = new CmsShoppingCart.TransactionWebService.insertRecordsRequestBody();
            inValue.Body.trxnID = trxnID;
            inValue.Body.nameOnCard = nameOnCard;
            inValue.Body.CardNumber = CardNumber;
            inValue.Body.unitPrice = unitPrice;
            inValue.Body.qty = qty;
            inValue.Body.totalPrice = totalPrice;
            inValue.Body.expDate = expDate;
            inValue.Body.creditCardType = creditCardType;
            inValue.Body.cardNum = cardNum;
            return ((CmsShoppingCart.TransactionWebService.TrxnWebService)(this)).insertRecordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CmsShoppingCart.TransactionWebService.deleteResultsResponse CmsShoppingCart.TransactionWebService.TrxnWebService.deleteResults(CmsShoppingCart.TransactionWebService.deleteResultsRequest request) {
            return base.Channel.deleteResults(request);
        }
        
        public string deleteResults(int trxId) {
            CmsShoppingCart.TransactionWebService.deleteResultsRequest inValue = new CmsShoppingCart.TransactionWebService.deleteResultsRequest();
            inValue.Body = new CmsShoppingCart.TransactionWebService.deleteResultsRequestBody();
            inValue.Body.trxId = trxId;
            CmsShoppingCart.TransactionWebService.deleteResultsResponse retVal = ((CmsShoppingCart.TransactionWebService.TrxnWebService)(this)).deleteResults(inValue);
            return retVal.Body.deleteResultsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CmsShoppingCart.TransactionWebService.deleteResultsResponse> CmsShoppingCart.TransactionWebService.TrxnWebService.deleteResultsAsync(CmsShoppingCart.TransactionWebService.deleteResultsRequest request) {
            return base.Channel.deleteResultsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CmsShoppingCart.TransactionWebService.deleteResultsResponse> deleteResultsAsync(int trxId) {
            CmsShoppingCart.TransactionWebService.deleteResultsRequest inValue = new CmsShoppingCart.TransactionWebService.deleteResultsRequest();
            inValue.Body = new CmsShoppingCart.TransactionWebService.deleteResultsRequestBody();
            inValue.Body.trxId = trxId;
            return ((CmsShoppingCart.TransactionWebService.TrxnWebService)(this)).deleteResultsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CmsShoppingCart.TransactionWebService.updateTransactionResponse CmsShoppingCart.TransactionWebService.TrxnWebService.updateTransaction(CmsShoppingCart.TransactionWebService.updateTransactionRequest request) {
            return base.Channel.updateTransaction(request);
        }
        
        public string updateTransaction(int trxnID, string nameOnCard, string CardNumber, double unitPrice, int qty, double totalPrice, string expDate, string creditCardType, long cardNum) {
            CmsShoppingCart.TransactionWebService.updateTransactionRequest inValue = new CmsShoppingCart.TransactionWebService.updateTransactionRequest();
            inValue.Body = new CmsShoppingCart.TransactionWebService.updateTransactionRequestBody();
            inValue.Body.trxnID = trxnID;
            inValue.Body.nameOnCard = nameOnCard;
            inValue.Body.CardNumber = CardNumber;
            inValue.Body.unitPrice = unitPrice;
            inValue.Body.qty = qty;
            inValue.Body.totalPrice = totalPrice;
            inValue.Body.expDate = expDate;
            inValue.Body.creditCardType = creditCardType;
            inValue.Body.cardNum = cardNum;
            CmsShoppingCart.TransactionWebService.updateTransactionResponse retVal = ((CmsShoppingCart.TransactionWebService.TrxnWebService)(this)).updateTransaction(inValue);
            return retVal.Body.updateTransactionReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CmsShoppingCart.TransactionWebService.updateTransactionResponse> CmsShoppingCart.TransactionWebService.TrxnWebService.updateTransactionAsync(CmsShoppingCart.TransactionWebService.updateTransactionRequest request) {
            return base.Channel.updateTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CmsShoppingCart.TransactionWebService.updateTransactionResponse> updateTransactionAsync(int trxnID, string nameOnCard, string CardNumber, double unitPrice, int qty, double totalPrice, string expDate, string creditCardType, long cardNum) {
            CmsShoppingCart.TransactionWebService.updateTransactionRequest inValue = new CmsShoppingCart.TransactionWebService.updateTransactionRequest();
            inValue.Body = new CmsShoppingCart.TransactionWebService.updateTransactionRequestBody();
            inValue.Body.trxnID = trxnID;
            inValue.Body.nameOnCard = nameOnCard;
            inValue.Body.CardNumber = CardNumber;
            inValue.Body.unitPrice = unitPrice;
            inValue.Body.qty = qty;
            inValue.Body.totalPrice = totalPrice;
            inValue.Body.expDate = expDate;
            inValue.Body.creditCardType = creditCardType;
            inValue.Body.cardNum = cardNum;
            return ((CmsShoppingCart.TransactionWebService.TrxnWebService)(this)).updateTransactionAsync(inValue);
        }
    }
}
